version: '3.6'
services:
  postgres:
    image: postgres:13.2
    ports:
    - "5432:5432"
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ankit
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: guild-chat
  guild-chat-server:
    image: anqit/guild-chat:latest
    stdin_open: true
    depends_on:
    - "postgres"
    ports:
    - "8080:8080"
    environment:
      DB_PROFILE: "local.docker.postgres"
  guild-chat-frontend:
    image: anqit/guild-chat-front:latest
    depends_on:
      - "guild-chat-server"
    ports:
      - "5000:5000"
    environment:
      API_ENDPOINT: "guild-chat-server:8080"

volumes:
  db_data:
    driver: local
